version: '3'
services:
  app:
    container_name: 'social-network-api'
    build: .
    restart: 'always'
    ports:
      - 3005:3005
    links:
      - mongo
  mongo:
    container_name: 'social-network-mongo'
    image: mongo
    restart: 'always'
    ports:
      - 27017:27017